spring:
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://lisanstudy.c5sc7zsexlq4.ap-northeast-2.rds.amazonaws.com:3306/innodb
      username: LisanStudy
      password: 1san1san
      
   mvc:
      static-path-pattern: /resources/**
   thymeleaf:
    cache: false

mybatis: 
  type-aliases-package: com.spring.yagaza.web.domain
  mapper-locations: classpath:mappers/*.xml
  configuration:
    default-statement-timeout: 120
    map-underscore-to-camel-case: true
    
